trigger:
- master

resources:
- repo: self

variables:
  #tag: '$(Build.BuildId)'
  tag: 23

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    #- task: Docker@2
     # inputs:
      #  containerRegistry: 'in28min-docker-hub'
      #  repository: 'in28min/currency-exchange-devops'
      #  command: 'buildAndPush'
       # Dockerfile: '**/Dockerfile'
      #  tags: '$(tag)'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/*.yaml'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'manifest'
        publishLocation: 'Container'
- stage: Deploy
  displayName: Deploy image
  jobs:  
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:   
    - task: DownloadBuildArtifacts@1
      inputs:
       buildType: 'current'
       downloadType: 'single'
       artifactName: 'manifest'
       itemPattern: '**/*.yaml'
       downloadPath: '$(System.ArtifactsDirectory)'
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'azurekubernetes'
        namespace: 'default'
        manifests: '$(System.ArtifactsDirectory)/configuration/kubernetes/deployment.yaml'
        containers: 'in28min/currency-exchange-devops:$(tag)'